# Alpine Linux with OpenJDK JRE
FROM openjdk:8-jre-alpine
# copy JAR into image
COPY /target/employee-0.0.1-SNAPSHOT.war /app.war
 
# Web port.
EXPOSE 8080

# run application with this command line 
CMD ["/usr/bin/java", "-jar", "-Dspring.profiles.active=default", "/app.war"]
